Script started on 2015年03月17日 (週二) 13時38分05秒
]0;C44021032@2015cpp: ~/lab1C44021032@2015cpp:~/lab1$ whoami;pwd
C44021032
/home/C44021032/lab1
]0;C44021032@2015cpp: ~/lab1C44021032@2015cpp:~/lab1$ git config -l
user.name=balilarder
user.email=balilarder@yahoo.com.tw
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
remote.origin.url=https://github.com/balilarder/lab1.git
branch.master.remote=origin
branch.master.merge=refs/heads/master
]0;C44021032@2015cpp: ~/lab1C44021032@2015cpp:~/lab1$ git clone[K[K[K[K[K[K[K[K[Kls
[0m[01;32mlab1_B[0m  lab1_B.cpp  lab1_B.script  lab1.script  README.txt
]0;C44021032@2015cpp: ~/lab1C44021032@2015cpp:~/lab1$ ./lab1_B
input n:
22
22 11 34 17 52 26 13 40 20 10 5 16 8 4 2 1
]0;C44021032@2015cpp: ~/lab1C44021032@2015cpp:~/lab1$ exit

Script done on 2015年03月17日 (週二) 13時39分38秒
